#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import agent.tasks
import os

request = json.load(sys.stdin)

agent.set_env('WEB_EXTERNAL_URL', request['path'])

response = agent.tasks.run(
    agent_id=agent.resolve_agent_id('traefik@node'),
    action='set-route',
    data={
        'instance': os.environ['MODULE_ID'],
        'url':  'http://127.0.0.1:' + os.environ["TCP_PORT"],
        'http2https': False,
        'lets_encrypt': False,
        'path': request['path'],
    },
)

# Check if traefik configuration has been successfull
agent.assert_exp(response['exit_code'] == 0)
