#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os

config = {
        'path': os.environ['WEB_EXTERNAL_URL'],
        }

json.dump(config, fp=sys.stdout)
